from django.db import models
from django.contrib.auth.models import User

class UserPlanStatus(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    has_diet_plan = models.BooleanField(default=False)
    has_workout_plan = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class GeneratedPlan(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="generated_plan"
    )

    diet_plan = models.JSONField(
        blank=True,
        null=True,
        help_text="Diet plan generated by Gemini"
    )

    workout_plan = models.JSONField(
        blank=True,
        null=True,
        help_text="Workout plan generated by Gemini"
    )

    safety_tips = models.JSONField(
        blank=True,
        null=True,
        help_text="Health & safety tips"
    )

    generated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} | Generated Plan"
