# Generated by Django 6.0.1 on 2026-01-25 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=18)),
                ('height_cm', models.FloatField(default=170)),
                ('weight_kg', models.FloatField(default=60)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('general_fitness', 'General Fitness'), ('endurance', 'Endurance')], default='general_fitness', max_length=30)),
                ('target_weight_kg', models.FloatField(default=60)),
                ('goal_timeframe_months', models.PositiveIntegerField(default=3, help_text='Time to achieve goal in months')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light Active'), ('moderate', 'Moderate'), ('very_active', 'Very Active')], default='sedentary', max_length=20)),
                ('fitness_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('workout_days_per_week', models.PositiveIntegerField(default=3)),
                ('workout_duration_minutes', models.PositiveIntegerField(default=45)),
                ('workout_preferences', models.JSONField(blank=True, help_text='gym, home, cardio, strength, yoga, hiit', null=True)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan')], default='vegetarian', max_length=20)),
                ('meals_per_day', models.PositiveIntegerField(default=3)),
                ('water_intake', models.CharField(choices=[('less_1', 'Less than 1L'), ('1_2', '1-2 Liters'), ('2_3', '2-3 Liters'), ('more_3', 'More than 3 Liters')], default='1_2', max_length=10)),
                ('food_allergies', models.JSONField(blank=True, null=True)),
                ('sleep_hours', models.CharField(choices=[('less_5', '< 5 hours'), ('5_6', '5-6 hours'), ('6_7', '6-7 hours'), ('7_8', '7-8 hours'), ('more_8', '> 8 hours')], default='7_8', max_length=10)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10)),
                ('health_conditions', models.JSONField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
