# Generated by Django 6.0.1 on 2026-01-25 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_plan', models.JSONField(help_text='Diet plan generated by Gemini')),
                ('workout_plan', models.JSONField(help_text='Workout plan generated by Gemini')),
                ('safety_tips', models.JSONField(blank=True, help_text='Health & safety tips', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
