# Generated by Django 6.0.1 on 2026-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_generatedplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedplan',
            name='diet_plan',
            field=models.JSONField(blank=True, help_text='Diet plan generated by Gemini', null=True),
        ),
        migrations.AlterField(
            model_name='generatedplan',
            name='workout_plan',
            field=models.JSONField(blank=True, help_text='Workout plan generated by Gemini', null=True),
        ),
    ]
